# Generated by Django 6.0.5 on 2026-06-06 19:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголовок поста", max_length=50, verbose_name="Заголовок"),
                ),
                ("content", models.TextField(help_text="Напишите ваш пост", verbose_name="Контент")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение для поста",
                        null=True,
                        upload_to="blog/images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "posted_by",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Укажите дату публикации",
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Отметьте, если пост опубликован", verbose_name="Опубликован"
                    ),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите количество просмотров", verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
        ),
    ]
